### ISSUE TITLE
API for accessing MediaWiki info set in LocalSettings.php, etc?

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#114]
Canasta currently has no way to access the info stored in `LocalSettings.php`, so it can't, for instance, detect the database name. Can we make an API for doing this?

**Comment by yaronkoren** [comment]
I agree that this would be useful, but, rather than API action(s), I think this would be best implemented as a command-line script inserted within MediaWiki - it seems like it would be more secure, so that regular users couldn't access this information. But maybe by "API" you didn't necessarily mean the literal MW API.

**Comment by jeffw16** [comment]
> But maybe by "API" you didn't necessarily mean the literal MW API.

Correct, APIs come in many forms, and I should've been more clear that this should not be a web API.

> I think this would be best implemented as a command-line script inserted within MediaWiki 

I completely agree!

> it seems like it would be more secure, so that regular users couldn't access this information

Completely agreed; in fact, I see no reason why a regular user should be using this proposed API.

**Comment by yaronkoren** [comment]
This is done now.
