### ISSUE TITLE
Load Bootstrap extension if Chameleon loaded during manual (non-CLI) install

### ISSUE THREAD

**Issue by lotusccong** [CanastaWiki/Canasta#148]
I followed the steps to manually install and create a new wiki site. After Mediawiki finished the installation and created the LocalSetting.php . I did copy the LocalSetting.php into config/
Run docker-compose down, then docker-compose up -d  .
When I access to https://localhost .
It showed this error message
localhost is currently unable to handle this request.
HTTP ERROR 500

The LocalSetting.php as below

<?php
# This file was automatically generated by the MediaWiki 1.35.8
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "True Buddha Canasta";
$wgMetaNamespace = "True_Buddha_Canasta";

## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://localhost";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@🌻.invalid";
$wgPasswordSender = "apache@🌻.invalid";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "db";
$wgDBname = "my_wiki";
$wgDBuser = "root";
$wgDBpassword = "mediawiki";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## localise the wiki.
$wgShellLocale = "C.UTF-8";

## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "5f8726ae5dfa4d24b4cef4d86f33f9f6bb02867d1887cab172999c2ab649e18a";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "7eb104780b2e864a";

## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'chameleon' );
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'pivot' );
wfLoadSkin( 'Refreshed' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# End of automatically generated settings.
# Add more configuration options below.

**Comment by jeffw16** [comment]
Immediately after the next time you visit https://localhost, please run:

sudo docker compose logs web

And see what the bottom of the output shows. If nothing abnormal appears, then try to run

sudo docker compose exec web tail /var/log/apache2/error.log

**Comment by lotusccong** [comment]
Got these error message :

debian@debian11:~$ sudo docker compose logs web
no configuration file provided: not found
debian@debian11:~$ sudo docker compose exec web tail /var/log/apache2/error.log
no configuration file provided: not found

**Comment by lotusccong** [comment]
Got this error message -
debian@debian11:~$ sudo docker compose logs web
no configuration file provided: not found
debian@debian11:~$ sudo docker compose exec web tail /var/log/apache2/error.log
no configuration file provided: not found

**Comment by lotusccong** [comment]
Got this error message
debian@debian11:~$ sudo docker compose logs web
no configuration file provided: not found
debian@debian11:~$ sudo docker compose exec web tail /var/log/apache2/error.log
no configuration file provided: not found

**Comment by amalpaul54111** [comment]
> I followed the steps to manually install and create a new wiki site. After Mediawiki finished the installation and created the LocalSetting.php . I did copy the LocalSetting.php into config/ Run docker-compose down, then docker-compose up -d . When I access to https://localhost . It showed this error message localhost is currently unable to handle this request. HTTP ERROR 500

I too had the same issue when I tried it. This could be due to this particular line, ``` wfLoadSkin( 'chameleon' ); ``` in ```LocalSettings.php```.  As the web container's log does show 
```
PHP Fatal error:  Uncaught ExtensionDependencyError: chameleon requires Bootstrap to be installed.
```

**Comment by lotusccong** [comment]
Hi Amal, 
Yes, you are right. After removed wfLoadSkin( 'chameleon' );. It works. :-).

**Comment by yaronkoren** [comment]
Sorry that I'm responding so late. Does anyone know how all those skins are getting automatically enabled in Canasta? I thought only Vector was automatically enable.

**Comment by jeffw16** [comment]
I think this started happening with Canasta 1.2.0, when the symlinking resulted in all skins being loaded in the skins directory automatically. I am guessing MediaWiki automatically loaded these skins into LocalSettings.php during the setup process. We should find a way to stop this from happening, since we already preload Vector.

**Comment by yaronkoren** [comment]
Okay, that's obviously really bad, if so. I just changed the title again to make this clearer - sorry for overwriting your change.

**Comment by jeffw16** [comment]
I like your new title better Yaron, thanks!

**Comment by yaronkoren** [comment]
Sorry, I changed the title yet again, now that I think I better understand this issue. The problem, I think, comes when using the standard MediaWiki installer GUI - which includes checkboxes (checked by default) for enabling all the existing skins. We could try to change the GUI - but maybe the better solution is to make sure that the Bootstrap extension gets loaded if the Chameleon skin does.

**Comment by yaronkoren** [comment]
Okay, having looked more into this (and talked it over with @gitmapd), I think the problem is in this file, in core MediaWiki:

https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/installer/LocalSettingsGenerator.php

It takes all the extensions and skins that the user selected in the GUI, and adds a wfLoad...() call for each one of them to LocalSettings.php. Unfortunately, it ignores any requirements that any of those extensions and skins have. Also unfortunately, it doesn't contain any hooks or some such to let us add to the set of extensions or skins.

I suppose the ideal fix would be to get a patch in to this file to have it read every extension.json and skin.json file of the selected extensions and skins, find all the requirements, and then include those also. I don't know how easy that would be to get into core MediaWiki, though. For now, I think we should just locally patch this file, to have it include some code like "if the set of skins includes Chameleon, and the set of extensions does not include Bootstrap, add Bootstrap to the set of extensions". Ideally within the __construct() function.

There are other required extensions and so forth - all the SMW-based extensions obviously require SMW - but this Chameleon one is the most notable, I think, because the GUI installer checks all the skin checkboxes by default (and none of the extension checkboxes). Clearly, based on the bug reports, Chameleon/Bootstrap is the big one. But in theory the code could handle other requirements also.

This would be, I think, our first-ever patch to core MediaWiki - which is kind of annoying, but I don't see another real solution here.

**Comment by jeffw16** [comment]
I support the patch for now. Thank you @gitmapd for helping to investigating! Many kudos go to you.

**Comment by yaronkoren** [comment]
Cool. I just want to correct my earlier statement: Canasta does indeed already have two patches to core MediaWiki - I didn't realize that before. But they're both going away, I think, with MW 1.39, so this new patch will then be the only core patch. (And one of very few patches in general.)
