### ISSUE TITLE
Proposing a new batch of extensions

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#192]
I propose adding the following, mostly SMW-related, extensions:

Modern Timeline
Semantic Glossary
Semantic Cite
SemanticDependencyUpdater
Semantic Meta Tags
Delete Batch
Import Users
~MatomoAnalytics~
WhosOnline
Mermaid
PageProperties
RightFunctions
RSS feed
Title Icon
NativeSvgHandler
~EmailLogger~
Mpdf
ParserHooks
Validator (comes with Maps and SMW)

**Comment by yaronkoren** [comment]
Hi @jeffw16 - thanks for putting this list together; it's an interesting list, and it's always good to re-evaluate the set of extensions we have. I subdivided these extensions into my own groupings, based almost entirely on my personal opinions and what I know about each of these extensions. In some cases, that's some much, so please just take these as my current opinion.

### Invalid

- ParserHooks, Validator - these both get installed along with SMW, I think
- Semantic Extra Special Properties - already included in Canasta

### Dubious

- Semantic Glossary - I'm biased, because I'm not a huge fan of SMW in general, but I especially don't like the use of SMW to store wiki-specific data (or "metadata"). Better would be some parser function, like "#glossary", that stored all the data in the page_props table. That's not how the Lingo extension works either, from what I understand; perhaps the ideal glossary extension doesn't exist yet.
- Semantic Cite - seems really pointless; as far as I can tell, it doesn't do anything that you can't already do by adding a #subobject call to a template like "Cite web"
- Semantic Meta Tags - I don't see the point of this one either; I think all the meta tag stuff is handled fine by the WikiSEO extension.
- ImportUsers - it's apparently [unmaintained](https://www.mediawiki.org/wiki/Extension:ImportUsers).
- WhosOnline - seems intrusive; and how does it help?
- PageProperties - maybe I'm misunderstanding this extension, but it seems to create an alternate system for editing and display of data that I think is better done with Page Forms instead.

### Iffy

- Modern Timeline - why isn't this part of Semantic Result Formats?
- Mpdf - I have nothing against this extension in theory (I actually contributed to it), but MediaWiki's default PDF printing (i.e., hit Ctrl+P, save as PDF) has gotten better, I think, and I also think [DocBookExport](https://www.mediawiki.org/wiki/Extension:DocBookExport), which (full disclosure) I helped design, is the better overall solution - it lets you create a document holding multiple wiki pages. We haven't been able to get DocBookExport into Canasta yet due to its dependencies, but hopefully that can happen at some point.
- RightFunctions - how useful is this?
- RSS feed - I assume you mean the RSS extension. It seems reasonable, but on the other hand, in theory all RSS display stuff can be handled via the External Data extension.
- MatomoAnalytics - we've discussed adding this one before, but it was in the context of also adding Matomo itself to Canasta. Would it be weird to include this extension without including Matomo?
- NativeSvgHandler - I don't really understand this one. What's the problem with default handling of SVG files?

### Seems good

- SemanticDependencyUpdater
- DeleteBatch
- Mermaid
- Title Icon
- EmailLogger

**Comment by freephile** [comment]
I like a lot of these suggestions.

Page Properties is particularly interesting bc I think Thomas has done very interesting work to leverage core MediaWiki functionality so that the extension is more 'native'.

**Comment by freephile** [comment]
btw, **Who's Online** shows a list of all active sessions, not viewers of a particular page.

Also, there are positional arguments you can pass to limit the list, and include navigational controls for viewing the list.

**Comment by yaronkoren** [comment]
Oh, okay - I misunderstood the [explanation](https://www.mediawiki.org/wiki/Extension:WhosOnline) of the extension: "viewing the list of users currently viewing a page on the wiki." I thought it meant a specific page. I still think this extension is unnecessary, but it's less intrusive than I thought.

**Comment by jeffw16** [comment]
Thanks for the input so far, everyone!

I'm okay with dropping all of the extensions under Yaron's invalid category, as well as ImportUsers, but the rest I would still like to see added to Canasta.

My thought is, Canasta should be about providing choice to its users. Even if there is already one way to do it in Canasta, it might not be their favorite choice, and it might not even work for their use case. Instead of requiring them to do it a certain way with the existing Canasta extensions, I think actively maintained extensions should still be included irrespective of whether its functionality could be similarly done with another Canasta extension, with the exception of extensions that really just seem to do a pure subset or the exact same thing as another.

The Semantic MediaWiki extensions might not be everyone's cup of tea, but it is used by lots of people, so I think there are still merits of adding it to Canasta.

**Comment by bryandamon** [comment]
I like WhosOnline and have used it on all the enterprise wikis I've been associated with, I generally don't think there's a right to anonymity in a corporate wiki.  I also use Wiretap which really is intrusive, but again fine in my opinion for corporate wikis.

I've never used RightFunctions, but it looks interesting.  I usually use UserFunctions to find the group a user is in, but having access to rights vs. groups might be nicer in some cases.

I usually use the Nuke extension for mass page deletion, how does DeleteBatch compare?

**Comment by yaronkoren** [comment]
Some thoughts/responses:
- SMW is indeed used by a lot of people, but that doesn't mean all the SMW-based extensions are. I've seen no evidence, for example, that anyone has ever used the Semantic Meta Tags extension.
- @bryandamon - can you explain why you like WhosOnline? I'm surprised, because it still seems so pointless to me.
- DeleteBatch is different from Nuke in that Nuke deletes all the pages created by certain users/IP addresses, whereas with DeleteBatch you manually specify the set of pages you want to delete. There's already a deleteBatch.php command-line script, but this lets you do the same thing from the web interface.
- There's still the more general question of what the philosophy for including extensions (and for that matter, skins) should be: should Canasta remain a sort of best practices bundle, or should it expand to basically try to include everything that works. (Or something else.) I'm curious to hear anyone's opinions on this.

**Comment by bryandamon** [comment]
WhosOnline is nice for corporations to get some idea about wiki usage.

**Comment by WaqarTabish2807** [comment]
> * There's still the more general question of what the philosophy for including extensions (and for that matter, skins) should be: should Canasta remain a sort of best practices bundle, or should it expand to basically try to include everything that works. (Or something else.) I'm curious to hear anyone's opinions on this.


Hey @yaronkoren. I would like to share my opinion on this :)). 

Best practices: As you mentioned, one approach could be to focus on including extensions and skins that adhere to best practices and are well-maintained, as this could help to ensure that the software is of high quality and easy to use.

Features: Another approach could include as many extensions and skins as possible to provide users with a wide range of features and customization options. However, this could lead to a larger and more complex software package, which is more difficult to maintain and has a higher learning curve for users.

Compatibility: The maintainers may consider compatibility when deciding which extensions and skins to include. For example, they may choose only to include extensions and skins compatible with the latest version of Canasta to ensure that the software is stable and works well.

Ultimately, the decision will depend on what works best for the maintainers.

**Comment by WolfgangFahl** [comment]
[SemanticCite](https://www.mediawiki.org/wiki/Extension:Semantic_Cite) has a specialpage Special:FindCitableMetadata for searching scholary articles. See https://github.com/SemanticMediaWiki/SemanticCite .This is the main feature i am using. SemanticCite seems to be broken for SMW 4. I would also consider it somewhat[unmaintained](https://github.com/SemanticMediaWiki/SemanticCite/graphs/contributors) since  https://github.com/mwjames was the main contributor but would love to see it live. As a work around i am using the scite markup of http://sotsog.bitplan.com/ these days.

**Comment by jeffw16** [comment]
@thomas-topway-it is working on maintaining and improving Semantic Cite, so rumors of Semantic Cite's demise have been greatly exaggerated ;)

**Comment by thomas-topway-it** [comment]
> <quote>PageProperties - maybe I'm misunderstanding this extension, but it seems to create a complex alternate system for editing and display of data that I think is better done with Page Forms instead.</quote>

I wanted to comment this passage.
This is certainly true for PageProperties prior to version 1.2.4, it was rather a demo for the use of an alternate way to record and to use semantic properties using slots.
By the way with the latest version it includes a form composer functionality and I think is finally usable.
It now supports page name formulas and input values formulas, and it is completely based on OOUI.
In future, I would like to add a file upload to record files completed with a path (that is under specific pages, so that you don't have to bother about unique filenames)
And of course select input options based on properties values, and so on.

**Comment by yaronkoren** [comment]
Well, this has gotten complicated - maybe no surprise, given that this is an issue about adding 20 different extensions. :) There are a bunch of questions here: what should the Canasta inclusion policy be in general, which of these specific extensions are useful, which of them will actually work with MW 1.39, etc. They're all somewhat tied in to one another, but I just don't think that having a single GitHub page for discussing all of them at the same time is workable. Of course, it would be nice to at least decide on the inclusion policy, but no one has really expressed a strong opinion on that yet.

@jeffw16 - what about creating a separate task issue, just for including those extensions that you think should definitely be included in the upcoming MW 1.39 version of Canasta? Assuming it's substantially less than 20 extensions - otherwise, it probably won't help much.

As far as the Canasta inclusion policy: I do believe it should be kept as it is, meaning that (in addition to just basic questions of whether each extension works) there should also be an element of curation, where every extension counts in some way as "best practices" for what it's trying to do. One strong argument in favor of keeping it this way is simply keeping the maintenance of Canasta manageable: Canasta already has nearly 150 extensions, and that's _with_ curation. What if we just allowed in every extension that anyone asked about? That number could double or even triple. I just don't know if it's sustainable. (Let alone how useful the massive selection would be, but that's another story.)

**Comment by WolfgangFahl** [comment]
I'd love to see some more metadata on the propopsed extensions along the lines of https://wiki.bitplan.com/index.php/List_of_Extensions

**Comment by yaronkoren** [comment]
@WolfgangFahl - if you want that, please create a separate issue for it. I'm trying to reduce the number of topics being discussed on this page, not increase it. :)

**Comment by yaronkoren** [comment]
After further discussions, I now think the following extensions from the original list should be added to Canasta:

- SemanticDependencyUpdater
- DeleteBatch
- Mermaid
- Title Icon
- WhosOnline

In addition, I'm indifferent as to the RSS extension.

**Comment by yaronkoren** [comment]
I'm closing this, since some of the extensions got added in, and the discussion in general seems to have died out. But if anyone wants any specific extensions (or skins!) added to Canasta, whether they're on this list or not, feel free to create individual GitHub issues for them.
