### ISSUE TITLE
Add EditAccount extension

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#259]
https://www.mediawiki.org/wiki/Extension:EditAccount is needed for one of WikiWorks clients

**Comment by yaronkoren** [comment]
Regardless of whether it's needed by a WikiWorks client, this seems like a reasonable extension to add. Although I think that "security risk" warning at the top of its mediawiki.org page should be removed, or replaced, before it can be added to Canasta, to prevent scaring users.

**Comment by tosfos** [comment]
Will do.

**Comment by tosfos** [comment]
@yaronkoren What do you think about the new warning? https://www.mediawiki.org/w/index.php?title=Extension:EditAccount&oldid=6013037

**Comment by yaronkoren** [comment]
Wow! Still scary, but less so. I removed the last sentence, but otherwise it looks good. (Of course, that's just me acting as a mediawiki.org editor - feel free to re-add the sentence if you want.)

Anyway, this seems like a reasonable extension to add, and now it seems fine to me. Does anyone object to adding it? Maybe we should give it a few days to lodge any objections.

**Comment by yaronkoren** [comment]
Okay, it's in! Well, this and SemanticTasks, now.
