### ISSUE TITLE
Releases for ghcr.io/canastawiki/canasta

### ISSUE THREAD

**Issue by coltonfreeman26** [CanastaWiki/Canasta#261]
Hello all,
I am new to the ghcr.io scene. I was wondering if there is somewhere I could view all the releases of ghcr.io/canastawiki/canasta? As far as I know there is 1.3.0, 1.3.1-pre and 1.39.1-latest we are wanting to pull the latest stable. Are all of these stable? I would assume 1.3.1-pre is not but am having trouble finding any docs on this. 

Also is 1.39.1-latest the same as 1.3.1-pre?

**Comment by jeffw16** [comment]
Apologies for the confusion. We recently moved to a new release system where we have a stable version and a "latest" version for two different audiences.

`1.3.0` is technically the current stable version.

`-pre` is not stable, that's why it's called `-pre` :)

We should probably create a `stable` tag as well.
