### ISSUE TITLE
Remove Graph extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#476]
Apparently this extension has been abandoned _and_ poses a major security risk:

https://www.mediawiki.org/wiki/Extension:Graph

It sounds like there's a good argument for removing it even before the MW 1.43 version of Canasta comes out.

**Comment by labster** [comment]
More than likely Graph isn't working anyway, because it has JSONConfig as a dependency, and that isn't included -- at the very least it's needed for tests. (See #442 which I should probably just close).

Background on the bug: https://phabricator.wikimedia.org/T334940  The short version is that Vega is a powerful enough that any library that uses it can be XSS’ed pretty much by design.  I'd recommend removing Graph, since it's only safe in environments where you can trust all of your editors.
