### ISSUE TITLE
Order the files included in the settings/ directory

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#64]
Currently, we are globbing the `settings/` directory to load in all of the files under that directory. Globbing the `settings/` directory does not guarantee any ordering of the files. That can be dangerous, as the files would be loaded in a nondeterministic order, which can change the functionality of the wiki without warning. It would be best to load them by alphabetical order of the file names.

Here is how globbing currently works: https://github.com/CanastaWiki/Canasta/blob/7cc8b1a045f5ee5ce0c687d62cd44535dad3b2fe/_sources/canasta/CanastaDefaultSettings.php#L73

**Comment by pastakhov** [comment]
Flags on  documentation page https://www.php.net/manual/en/function.glob.php:
"GLOB_NOSORT - Return files as they appear in the directory (no sorting). When this flag is not used, the pathnames are sorted alphabetically " so, it is already sorted because we don't use  `GLOB_NOSORT` flag. I tested it and it is really sorted alphabetically.
